print("===== ANTRIAN PASIEN =====")
print("[1] P001 - Andi  | Flu")
print("[2] P002 - Budi  | Tifus")
print("[3] P003 - Cici  | Flu")
print("[4] P004 - Dani  | Maag")
print("Total antrian: 4")
print()
print("Memanggil pasien berikutnya...")
print("Silakan masuk: Andi (P001) - Flu")
print()
print("===== ANTRIAN PASIEN =====")
print("[1] P002 - Budi  | Tifus")
print("[2] P003 - Cici  | Flu")
print("[3] P004 - Dani  | Maag")
print("Total antrian: 3")
print()
print("Menghapus pasien dengan ID P003...")
print("Cici (P003) berhasil dihapus dari antrian.")
print()
print("===== ANTRIAN PASIEN =====")
print("[1] P002 - Budi  | Tifus")
print("[2] P004 - Dani  | Maag")
print("Total antrian: 2")
print()
print("Mencari 'Dani'...")
print("Ditemukan: P004 - Dani | Maag (posisi ke-2)")
print()
print("Total antrian: 2")
